services:
  - type: redis
    name: fx-pulse-redis
    plan: free
    ipAllowList: []

  - type: web
    name: fx-pulse-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/v1/ready
    envVars:
      - key: CORS_ORIGINS
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: REDIS_URL
        fromService:
          type: redis
          name: fx-pulse-redis
          property: connectionString

  - type: web
    name: fx-pulse-web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: .
    plan: free
